application:
  subdomain: poster
  multi_instance: false
  routes:
    - /=http://poster:80/
services:
  poster:
    # 监控流程会在构建 LPK 前将该地址替换为 copy-image 返回的官方镜像地址。
    # upstream: ghcr.io/wcaqrl/poster:0.1.1
    image: registry.lazycat.cloud/peter/wcaqrl/poster:ae8fc5c0af912517
    healthcheck:
      test:
        - CMD
        - wget
        - -q
        - -O
        - /dev/null
        - http://127.0.0.1/healthz
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
